<?php
/**
 * @file
 * os2web_mobile_feature.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function os2web_mobile_feature_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['menu_block-15'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => '15',
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bootstrap' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bootstrap',
        'weight' => '0',
      ),
      'cmstheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'cmstheme',
        'weight' => '0',
      ),
      'omega' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'omega',
        'weight' => '0',
      ),
    ),
    'title' => 'Borger',
    'visibility' => '0',
  );

  $export['menu_block-16'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => '16',
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bootstrap' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bootstrap',
        'weight' => '0',
      ),
      'cmstheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'cmstheme',
        'weight' => '0',
      ),
      'omega' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'omega',
        'weight' => '0',
      ),
    ),
    'title' => 'Erhverv',
    'visibility' => '0',
  );

  $export['menu_block-17'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => '17',
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bootstrap' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bootstrap',
        'weight' => '0',
      ),
      'cmstheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'cmstheme',
        'weight' => '0',
      ),
      'omega' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'omega',
        'weight' => '0',
      ),
    ),
    'title' => 'Politik og demokrati',
    'visibility' => '0',
  );

  $export['menu_block-18'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => '18',
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bootstrap' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bootstrap',
        'weight' => '0',
      ),
      'cmstheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'cmstheme',
        'weight' => '0',
      ),
      'omega' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'omega',
        'weight' => '0',
      ),
    ),
    'title' => '<none>',
    'visibility' => '0',
  );

  $export['menu_block-19'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => '19',
    'module' => 'menu_block',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bootstrap' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bootstrap',
        'weight' => '0',
      ),
      'cmstheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'cmstheme',
        'weight' => '0',
      ),
      'omega' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'omega',
        'weight' => '0',
      ),
    ),
    'title' => '<none>',
    'visibility' => '0',
  );

  return $export;
}
